import { JobBoard, PipelineItem, TargetCompany } from "./types";

export const defaultBoards: JobBoard[] = [
  {
    id: "1",
    name: "Upwork",
    url: "https://www.upwork.com/nx/find-work/best-matches",
    icon: "briefcase",
    status: "Daily",
    lastChecked: "2026-02-14",
    notes: "Primary income source. 574 connects.",
  },
  {
    id: "2",
    name: "Contra",
    url: "https://contra.com/opportunity/discover",
    icon: "palette",
    status: "Weekly",
    lastChecked: "",
    notes: "Mostly design roles, check for React/Next.js",
  },
  {
    id: "3",
    name: "Arc.dev",
    url: "https://arc.dev/developer/jobs",
    icon: "code",
    status: "Weekly",
    lastChecked: "",
    notes: "Profile complete",
  },
  {
    id: "4",
    name: "Braintrust",
    url: "https://app.usebraintrust.com/talents/dashboard",
    icon: "brain",
    status: "Pending",
    lastChecked: "",
    notes: "AI interview pending — Devblock + Freelance Labs",
  },
  {
    id: "5",
    name: "Wellfound",
    url: "https://wellfound.com/jobs",
    icon: "rocket",
    status: "Weekly",
    lastChecked: "",
    notes: "Better post-Navy for full-time",
  },
  {
    id: "6",
    name: "Toptal",
    url: "https://www.toptal.com",
    icon: "trophy",
    status: "Pending",
    lastChecked: "",
    notes: "Application submitted, awaiting screening",
  },
  {
    id: "7",
    name: "Freelancer.com",
    url: "https://www.freelancer.com/search/projects",
    icon: "hammer",
    status: "Weekly",
    lastChecked: "",
    notes: "Project-based freelance",
  },
  {
    id: "8",
    name: "HN Who's Hiring",
    url: "https://news.ycombinator.com/item?id=42575537",
    icon: "newspaper",
    status: "Weekly",
    lastChecked: "",
    notes: "Check Feb 2026 thread",
  },
  {
    id: "9",
    name: "LinkedIn",
    url: "https://www.linkedin.com/jobs",
    icon: "linkedin",
    status: "Weekly",
    lastChecked: "",
    notes: "Services enabled",
  },
];

export const defaultPipeline: PipelineItem[] = [
  {
    id: "1",
    client: "Mike / TavernSeat",
    platform: "Upwork",
    status: "Active",
    rate: "$5,700 total",
    lastContact: "2026-02-14",
    nextAction: "M3 call Monday",
    notes: "Collect $1,100",
  },
  {
    id: "2",
    client: "Peter / Lovify",
    platform: "Upwork",
    status: "Waiting",
    rate: "$55/hr",
    lastContact: "",
    nextAction: "Follow up Tuesday",
    notes: "NDA pending",
  },
  {
    id: "3",
    client: "Piotr / Supabase Audit",
    platform: "Upwork",
    status: "Waiting",
    rate: "$750",
    lastContact: "",
    nextAction: "Send email for repo access",
    notes: "",
  },
  {
    id: "4",
    client: "Habab / EdTech Platform",
    platform: "Upwork",
    status: "Waiting",
    rate: "$2,800-$13,500",
    lastContact: "",
    nextAction: "Wait for decision",
    notes: "Chose $2,800 infra scope",
  },
  {
    id: "5",
    client: "Anissa / Junk Removal Site",
    platform: "Direct",
    status: "Active",
    rate: "$500",
    lastContact: "",
    nextAction: "Collect final $250",
    notes: "Waiting on husband photo",
  },
  {
    id: "6",
    client: "Jeanne / Healthcare MVP",
    platform: "Upwork",
    status: "Interviewing",
    rate: "TBD",
    lastContact: "",
    nextAction: "Call tomorrow",
    notes: "Healthcare education platform",
  },
  {
    id: "7",
    client: "Fractional CTO Gamified SaaS",
    platform: "Upwork",
    status: "Submitted",
    rate: "$55/hr",
    lastContact: "",
    nextAction: "Wait",
    notes: "France-based client",
  },
  {
    id: "8",
    client: "Security Audit (GoodOfTheOrder)",
    platform: "Upwork",
    status: "Submitted",
    rate: "$400",
    lastContact: "",
    nextAction: "Wait",
    notes: "Supabase RLS review",
  },
  {
    id: "9",
    client: "Medical Fertility Site",
    platform: "Upwork",
    status: "Submitted",
    rate: "$1,500",
    lastContact: "",
    nextAction: "Wait",
    notes: "Greece-based client",
  },
  {
    id: "10",
    client: "Revenue Intelligence Dashboard",
    platform: "Upwork",
    status: "Submitted",
    rate: "$4,500",
    lastContact: "",
    nextAction: "Wait",
    notes: "Austin client, exact stack",
  },
  {
    id: "11",
    client: "React App Completion (Austin)",
    platform: "Upwork",
    status: "Submitted",
    rate: "$3,500",
    lastContact: "",
    nextAction: "Wait",
    notes: "Python backend gap",
  },
  {
    id: "12",
    client: "Recademics",
    platform: "Upwork",
    status: "Submitted",
    rate: "$65/hr",
    lastContact: "",
    nextAction: "Wait",
    notes: "Long shot, post-Navy target",
  },
  {
    id: "13",
    client: "Stripe Tap-to-Tip",
    platform: "Upwork",
    status: "Submitted",
    rate: "$50/hr",
    lastContact: "",
    nextAction: "Wait",
    notes: "Seattle startup",
  },
  {
    id: "14",
    client: "Iraqi EdTech Security Audit",
    platform: "Upwork",
    status: "Submitted",
    rate: "$1,000",
    lastContact: "",
    nextAction: "Wait",
    notes: "13K active users",
  },
  {
    id: "15",
    client: "Next.js SaaS Property Mgmt",
    platform: "Upwork",
    status: "Submitted",
    rate: "$15,000",
    lastContact: "",
    nextAction: "Wait",
    notes: "",
  },
  {
    id: "16",
    client: "WriterScribe AI",
    platform: "Upwork",
    status: "Submitted",
    rate: "$5,000",
    lastContact: "",
    nextAction: "Wait",
    notes: "Late, 14 interviewing",
  },
  {
    id: "17",
    client: "B2B AI Productivity App",
    platform: "Upwork",
    status: "Submitted",
    rate: "$5,000",
    lastContact: "",
    nextAction: "Wait",
    notes: "CRM integration gap",
  },
  {
    id: "18",
    client: "Security Audit (Duolingo-style)",
    platform: "Upwork",
    status: "Submitted",
    rate: "$50/hr",
    lastContact: "",
    nextAction: "Wait",
    notes: "15-20 proposals already",
  },
];

export const defaultTargets: TargetCompany[] = [
  {
    id: "1",
    name: "Recademics",
    description: "EdTech, Claude Code",
    salary: "$150-190K",
    details: "Remote, Southlake TX",
    contact: "",
  },
  {
    id: "2",
    name: "Freelance Labs / Braintrust",
    description: "$90/hr, product engineering",
    salary: "$90/hr",
    details: "Product engineering",
    contact: "",
  },
  {
    id: "3",
    name: "Streams",
    description: "Next.js startup",
    salary: "",
    details: "9-5 ET required",
    contact: "",
  },
  {
    id: "4",
    name: "Fueled",
    description: "Agency, Next.js + WordPress",
    salary: "",
    details: "Contract",
    contact: "",
  },
  {
    id: "5",
    name: "Blackbird",
    description: "Dev shop, TS/React/Postgres",
    salary: "",
    details: "Contract",
    contact: "vance@blackbird.us",
  },
];

export function generateId(): string {
  return Date.now().toString(36) + Math.random().toString(36).slice(2, 7);
}
